"""IBIS file writer — serializes IbisModel to IBIS-formatted text."""

from __future__ import annotations

from pathlib import Path

from spice_to_ibis.models.ibis import CornerFloat, IbisModel, Ramp, VIPoint, Waveform


def write_ibis(model: IbisModel, filepath: str | Path) -> None:
    """Write an IbisModel to an IBIS-formatted file."""
    filepath = Path(filepath)
    text = format_ibis(model, filepath.name)
    filepath.write_text(text)


def format_ibis(model: IbisModel, file_name: str = "") -> str:
    """Format an IbisModel as IBIS text."""
    lines: list[str] = []

    # Header
    lines.append("|*******************************************")
    lines.append("|* IBIS file generated by spice-to-ibis")
    lines.append("|*******************************************")
    lines.append("")

    # File-level keywords
    lines.append(f"[IBIS Ver]      {model.ibis_version}")
    lines.append(f"[File Name]     {file_name or model.file_name}")
    lines.append(f"[File Rev]      {model.file_revision}")
    lines.append("")

    # Component
    lines.append(f"[Component]     {model.component_name or 'unnamed'}")
    lines.append(f"[Manufacturer]  {model.manufacturer or 'unknown'}")
    lines.append("")

    # Package
    _write_corner_row(lines, "[Package]", "R_pkg", model.package_r)
    _write_corner_row(lines, "", "L_pkg", model.package_l)
    _write_corner_row(lines, "", "C_pkg", model.package_c)
    if model.package_r or model.package_l or model.package_c:
        lines.append("")

    # Pin
    lines.append("[Pin]  signal_name    model_name     R_pin  L_pin  C_pin")
    pin = model.pin_name or "1"
    sig = model.signal_name or pin
    mname = model.model_name or "unnamed"
    lines.append(f"  {pin:<6s}{sig:<15s}{mname}")
    lines.append("")

    # Model
    lines.append(f"[Model]         {model.model_name or 'unnamed'}")
    lines.append(f"Model_type      {model.model_type}")
    lines.append(f"Polarity        {model.polarity}")
    lines.append(f"Enable          {model.enable}")
    lines.append("")

    lines.append(f"Vinl = {model.vinl:.3f}V")
    lines.append(f"Vinh = {model.vinh:.3f}V")
    lines.append("")

    # C_comp
    if model.c_comp:
        _write_corner_row(lines, "C_comp", "", model.c_comp, unit="F")
        lines.append("")

    # Voltage range
    if model.voltage_range:
        lines.append(
            f"[Voltage Range]  {_fmt(model.voltage_range.typ)}  "
            f"{_fmt(model.voltage_range.min)}  "
            f"{_fmt(model.voltage_range.max)}"
        )
        lines.append("")

    # Temperature range
    if model.temperature_range:
        lines.append(
            f"[Temperature Range]  {_fmt(model.temperature_range.typ)}  "
            f"{_fmt(model.temperature_range.min)}  "
            f"{_fmt(model.temperature_range.max)}"
        )
        lines.append("")

    # V-I tables
    _write_vi_table(lines, "[Pulldown]", model.pulldown)
    _write_vi_table(lines, "[Pullup]", model.pullup)
    _write_vi_table(lines, "[GND Clamp]", model.gnd_clamp)
    _write_vi_table(lines, "[POWER Clamp]", model.power_clamp)

    # Ramp
    _write_ramp(lines, model.ramp)

    # Waveforms
    for wf in model.rising_waveform:
        _write_waveform(lines, "[Rising Waveform]", wf)

    for wf in model.falling_waveform:
        _write_waveform(lines, "[Falling Waveform]", wf)

    lines.append("[End]")
    lines.append("")

    return "\n".join(lines)


def _fmt(val: float) -> str:
    """Format a float for IBIS output."""
    if abs(val) < 1e-15:
        return "0"
    return f"{val:.6e}"


def _write_corner_row(
    lines: list[str],
    section: str,
    param: str,
    cf: CornerFloat | None,
    unit: str = "",
) -> None:
    if cf is None:
        return
    if section:
        lines.append(section)
    u = f" {unit}" if unit else ""
    lines.append(
        f"  {param:<12s}{_fmt(cf.typ)}{u}  {_fmt(cf.min)}{u}  {_fmt(cf.max)}{u}"
    )


def _write_vi_table(
    lines: list[str], header: str, points: list[VIPoint]
) -> None:
    if not points:
        return
    lines.append(header)
    lines.append("|  Voltage       I(typ)           I(min)           I(max)")
    for p in points:
        lines.append(
            f"  {_fmt(p.voltage):>14s}  {_fmt(p.typ_current):>14s}"
            f"  {_fmt(p.min_current):>14s}  {_fmt(p.max_current):>14s}"
        )
    lines.append("")


def _write_ramp(lines: list[str], ramp: Ramp | None) -> None:
    if ramp is None:
        return
    lines.append("[Ramp]")
    if ramp.dv_r and ramp.dt_r:
        lines.append(
            "| variable      typ             min             max"
        )
        lines.append(
            f"  dV/dt_r       {_fmt(ramp.dv_r.typ)}/{_fmt(ramp.dt_r.typ)}  "
            f"{_fmt(ramp.dv_r.min)}/{_fmt(ramp.dt_r.min)}  "
            f"{_fmt(ramp.dv_r.max)}/{_fmt(ramp.dt_r.max)}"
        )
    if ramp.dv_f and ramp.dt_f:
        lines.append(
            f"  dV/dt_f       {_fmt(ramp.dv_f.typ)}/{_fmt(ramp.dt_f.typ)}  "
            f"{_fmt(ramp.dv_f.min)}/{_fmt(ramp.dt_f.min)}  "
            f"{_fmt(ramp.dv_f.max)}/{_fmt(ramp.dt_f.max)}"
        )
    lines.append("")


def _write_waveform(
    lines: list[str], header: str, wf: Waveform
) -> None:
    if not wf.points:
        return
    lines.append(header)
    lines.append(f"R_fixture = {_fmt(wf.r_fixture)}")
    lines.append(f"V_fixture = {_fmt(wf.v_fixture)}")
    lines.append("|  Time          V(typ)           V(min)           V(max)")
    for p in wf.points:
        lines.append(
            f"  {_fmt(p.time):>14s}  {_fmt(p.typ_voltage):>14s}"
            f"  {_fmt(p.min_voltage):>14s}  {_fmt(p.max_voltage):>14s}"
        )
    lines.append("")
