"""IBIS file writer."""

from __future__ import annotations

from pathlib import Path

from spice_to_ibis.converter import IbisModel


def write_ibis(model: IbisModel, filepath: str | Path) -> None:
    """Write an IbisModel to an IBIS-formatted file.

    Args:
        model: The IBIS model data to write.
        filepath: Output file path.
    """
    filepath = Path(filepath)
    lines = [
        "|*******************************************",
        "|* IBIS file generated by spice-to-ibis",
        "|*******************************************",
        "",
        "[IBIS Ver]      7.0",
        "[File Name]     {}".format(filepath.name),
        "[File Rev]      0.1",
        "",
        "[Component]     {}".format(model.component_name or "unnamed"),
        "",
        "[Model]         {}".format(model.model_name or "unnamed"),
        "Model_type      {}".format(model.model_type or "I/O"),
        "",
        "[End]",
    ]
    filepath.write_text("\n".join(lines) + "\n")
